import { FEATNESS_COLORS, FEATNESS_RADIUS, FEATNESS_SPACING } from "./theme/colors";

export const theme = {
  colors: {
    background: "#07110f",
    backgroundSoft: "#0d1b18",
    surface: FEATNESS_COLORS.surface,
    surfaceStrong: "#152b26",
    surfaceMuted: "#0c1816",
    border: "rgba(216, 226, 220, 0.08)",
    borderStrong: "rgba(201, 166, 70, 0.22)",
    text: FEATNESS_COLORS.textPrimary,
    textMuted: FEATNESS_COLORS.textSecondary,
    textSoft: "#b9c8c2",
    gold: "#c9a646",
    goldSoft: "rgba(201, 166, 70, 0.14)",
    mint: FEATNESS_COLORS.primary,
    mintSoft: "rgba(16, 185, 129, 0.14)",
    danger: FEATNESS_COLORS.error,
    white: "#ffffff",
    ink: "#08110f",
    primary: FEATNESS_COLORS.primary,
    primaryDark: FEATNESS_COLORS.primaryDark,
    primaryLight: FEATNESS_COLORS.primaryLight,
    success: FEATNESS_COLORS.success,
    warning: FEATNESS_COLORS.warning,
    error: FEATNESS_COLORS.error,
    protein: FEATNESS_COLORS.protein,
    carbs: FEATNESS_COLORS.carbs,
    fat: FEATNESS_COLORS.fat,
    calories: FEATNESS_COLORS.calories,
  },
  radius: {
    sm: FEATNESS_RADIUS.sm,
    md: FEATNESS_RADIUS.md,
    lg: 20,
    xl: 28,
    pill: 999,
  },
  spacing: {
    xs: FEATNESS_SPACING.xs,
    sm: FEATNESS_SPACING.sm + 4,
    md: FEATNESS_SPACING.md + 4,
    lg: FEATNESS_SPACING.lg + 4,
    xl: FEATNESS_SPACING.xl,
    xxl: FEATNESS_SPACING.xxl,
  },
};

export const mobileShadow = {
  shadowColor: "#000000",
  shadowOpacity: 0.18,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 8 },
  elevation: 10,
} as const;
