export type EffortCategory = "light" | "medium" | "intense";

export type MealCatalogPresentation = {
  calories: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  preparationType: "lyophilise" | "auto_chauffant" | "assemblage_sec";
  accent: string;
  ingredients: string[];
  allergens: string[];
  ingredientNotes: string;
};

export const MEAL_PRESENTATION_BY_SLUG: Record<string, MealCatalogPresentation> = {
  "bowl-poulet-riz-courgette": {
    calories: 520,
    proteinG: 38,
    carbsG: 54,
    fatG: 14,
    preparationType: "auto_chauffant",
    accent: "#7bd39c",
    ingredients: ["Blanc de poulet", "Riz basmati", "Courgette", "Huile d'olive", "Sel", "Poivre", "Herbes de Provence"],
    allergens: [],
    ingredientNotes: "Recette recovery simple et digeste, ideale apres un effort leger a moyen avec glucides et proteines maigres.",
  },
  "omelette-sport-tartines-completes": {
    calories: 460,
    proteinG: 31,
    carbsG: 29,
    fatG: 22,
    preparationType: "auto_chauffant",
    accent: "#f3c76a",
    ingredients: ["Oeufs", "Blancs d'oeufs", "Pain complet", "Tomates", "Epinards", "Fromage frais leger", "Huile d'olive"],
    allergens: ["Oeufs", "Gluten", "Lait"],
    ingredientNotes: "Bon compromis post-seance courte avec proteines rapides et tartines completes pour recharger sans lourdeur.",
  },
  "skyr-bowl-banane-flocons-davoine": {
    calories: 390,
    proteinG: 26,
    carbsG: 46,
    fatG: 8,
    preparationType: "assemblage_sec",
    accent: "#6cd3ff",
    ingredients: ["Skyr", "Banane", "Flocons d'avoine", "Myrtilles", "Graines de chia", "Miel"],
    allergens: ["Lait", "Gluten"],
    ingredientNotes: "Option hydratation et recuperation legere, pratique dans l'heure suivant un cardio ou une seance moderee.",
  },
  "wrap-dinde-avocat": {
    calories: 470,
    proteinG: 33,
    carbsG: 34,
    fatG: 18,
    preparationType: "assemblage_sec",
    accent: "#82c9ad",
    ingredients: ["Tortilla complete", "Blanc de dinde", "Avocat", "Salade", "Tomate", "Fromage blanc", "Citron", "Poivre"],
    allergens: ["Gluten", "Lait"],
    ingredientNotes: "Wrap recovery rapide pour une faim moderee avec bon apport proteique et lipides utiles via l'avocat.",
  },
  "saumon-pommes-de-terre-haricots-verts": {
    calories: 560,
    proteinG: 34,
    carbsG: 40,
    fatG: 24,
    preparationType: "auto_chauffant",
    accent: "#9ad0ff",
    ingredients: ["Pave de saumon", "Pommes de terre", "Haricots verts", "Huile d'olive", "Citron", "Ail", "Sel", "Poivre"],
    allergens: ["Poisson"],
    ingredientNotes: "Plat complet recovery avec omega-3, pommes de terre digestes et legumes simples apres seance technique ou moderee.",
  },
  "porridge-proteine-post-cardio": {
    calories: 430,
    proteinG: 24,
    carbsG: 49,
    fatG: 13,
    preparationType: "assemblage_sec",
    accent: "#f0be73",
    ingredients: ["Flocons d'avoine", "Lait", "Banane", "Beurre de cacahuete", "Cannelle", "Skyr"],
    allergens: ["Lait", "Gluten", "Arachides"],
    ingredientNotes: "Base hydratation et glucides pour post-cardio avec texture simple a consommer juste apres effort.",
  },
  "poulet-patate-douce-brocoli": {
    calories: 610,
    proteinG: 42,
    carbsG: 58,
    fatG: 16,
    preparationType: "auto_chauffant",
    accent: "#8cc97f",
    ingredients: ["Blanc de poulet", "Patate douce", "Brocoli", "Huile d'olive", "Paprika", "Ail", "Sel", "Poivre"],
    allergens: [],
    ingredientNotes: "Reference FEATNESS pour recuperation serieuse apres muscu ou circuit training avec glucides lents et proteines maigres.",
  },
  "bowl-quinoa-thon-avocat": {
    calories: 540,
    proteinG: 32,
    carbsG: 41,
    fatG: 22,
    preparationType: "assemblage_sec",
    accent: "#7fd1d8",
    ingredients: ["Quinoa", "Thon au naturel", "Avocat", "Concombre", "Tomates cerises", "Mais", "Jus de citron", "Huile d'olive"],
    allergens: ["Poisson"],
    ingredientNotes: "Bowl tres pratique pour recuperer sans lourdeur avec bon equilibre entre glucides, proteines et hydration vegetale.",
  },
  "pates-completes-au-poulet": {
    calories: 690,
    proteinG: 39,
    carbsG: 78,
    fatG: 16,
    preparationType: "auto_chauffant",
    accent: "#f0a86e",
    ingredients: ["Pates completes", "Blanc de poulet", "Sauce tomate nature", "Courgette", "Parmesan", "Ail", "Basilic", "Huile d'olive"],
    allergens: ["Gluten", "Lait"],
    ingredientNotes: "Plat performance pour remonter le stock de glycogene apres effort moyen a intense avec base glucidique genereuse.",
  },
  "riz-boeuf-maigre-poivrons": {
    calories: 660,
    proteinG: 37,
    carbsG: 63,
    fatG: 19,
    preparationType: "auto_chauffant",
    accent: "#d88b74",
    ingredients: ["Riz jasmin", "Boeuf maigre", "Poivrons", "Oignon", "Sauce soja legere", "Ail", "Huile d'olive"],
    allergens: ["Soja"],
    ingredientNotes: "Version plus dense pour efforts moyens, utile quand il faut remonter l'energie tout en gardant des proteines solides.",
  },
  "chili-leger-recuperation": {
    calories: 640,
    proteinG: 36,
    carbsG: 61,
    fatG: 17,
    preparationType: "auto_chauffant",
    accent: "#c97768",
    ingredients: ["Haricots rouges", "Dinde hachee", "Riz", "Tomate concassee", "Oignon", "Ail", "Cumin", "Paprika"],
    allergens: [],
    ingredientNotes: "Plat recovery complet et rassasiant, tres pertinent apres musculation ou cardio boxing de duree moyenne.",
  },
  "salade-lentilles-oeufs-feta": {
    calories: 510,
    proteinG: 28,
    carbsG: 36,
    fatG: 22,
    preparationType: "assemblage_sec",
    accent: "#a5c98a",
    ingredients: ["Lentilles cuites", "Oeufs", "Feta", "Concombre", "Tomates", "Roquette", "Huile d'olive", "Vinaigre balsamique"],
    allergens: ["Oeufs", "Lait"],
    ingredientNotes: "Option recovery froide et pratique, avec bonnes fibres et proteines pour les jours de seance moyenne ou reprise.",
  },
  "burrito-bowl-dinde-riz": {
    calories: 700,
    proteinG: 40,
    carbsG: 75,
    fatG: 18,
    preparationType: "auto_chauffant",
    accent: "#f2b464",
    ingredients: ["Riz", "Dinde hachee", "Haricots noirs", "Mais", "Avocat", "Salsa tomate", "Salade", "Coriandre"],
    allergens: [],
    ingredientNotes: "Recette performance simple pour remonter haut les glucides apres une seance exigeante sans perdre le focus proteique.",
  },
  "cabillaud-semoule-legumes-rotis": {
    calories: 570,
    proteinG: 35,
    carbsG: 53,
    fatG: 14,
    preparationType: "auto_chauffant",
    accent: "#8fc7d9",
    ingredients: ["Cabillaud", "Semoule complete", "Carottes", "Courgettes", "Poivrons", "Huile d'olive", "Citron", "Epices douces"],
    allergens: ["Poisson", "Gluten"],
    ingredientNotes: "Plat tres propre pour recuperation ou performance moderee avec poisson maigre et semoule complete digeste.",
  },
  "saumon-riz-complet-avocat": {
    calories: 760,
    proteinG: 39,
    carbsG: 66,
    fatG: 30,
    preparationType: "assemblage_sec",
    accent: "#6fb4ff",
    ingredients: ["Saumon", "Riz complet", "Avocat", "Epinards", "Concombre", "Huile d'olive", "Citron", "Graines de sesame"],
    allergens: ["Poisson", "Sesame"],
    ingredientNotes: "Format intense avec bon volume glucidique et lipides utiles, pense pour course longue ou grosse seance jambes.",
  },
  "poulet-teriyaki-maison-nouilles-de-riz": {
    calories: 780,
    proteinG: 42,
    carbsG: 88,
    fatG: 14,
    preparationType: "auto_chauffant",
    accent: "#f3a95f",
    ingredients: ["Blanc de poulet", "Nouilles de riz", "Carottes", "Brocoli", "Sauce soja reduite en sel", "Miel", "Gingembre", "Ail"],
    allergens: ["Soja"],
    ingredientNotes: "Choix performance fort pour recharger vite apres effort intense ou sortie longue, avec gros focus glucides.",
  },
  "poke-bowl-thon-riz-mangue": {
    calories: 720,
    proteinG: 36,
    carbsG: 81,
    fatG: 17,
    preparationType: "assemblage_sec",
    accent: "#7fd8c0",
    ingredients: ["Riz", "Thon", "Mangue", "Concombre", "Avocat", "Edamame", "Sauce soja legere", "Citron vert", "Graines de sesame"],
    allergens: ["Poisson", "Soja", "Sesame"],
    ingredientNotes: "Poke performance tres lisible pour une recuperation haute en glucides tout en restant frais et digeste.",
  },
  "gnocchis-dinde-sauce-tomate": {
    calories: 740,
    proteinG: 38,
    carbsG: 86,
    fatG: 15,
    preparationType: "auto_chauffant",
    accent: "#e1937e",
    ingredients: ["Gnocchis", "Dinde hachee", "Sauce tomate nature", "Courgette", "Parmesan", "Ail", "Basilic", "Huile d'olive"],
    allergens: ["Gluten", "Lait"],
    ingredientNotes: "Recette performance genereuse pour les grosses depenses, avec dinde maigre et grosse base glucidique.",
  },
  "curry-de-poulet-riz-coco-leger": {
    calories: 760,
    proteinG: 39,
    carbsG: 79,
    fatG: 20,
    preparationType: "auto_chauffant",
    accent: "#e7b56d",
    ingredients: ["Blanc de poulet", "Riz basmati", "Lait de coco leger", "Carottes", "Courgette", "Pois chiches", "Curry", "Ail", "Oignon"],
    allergens: [],
    ingredientNotes: "Plat performance confortable et rassasiant quand la seance a ete tres exigeante et qu'il faut recharger fort.",
  },
  "bol-recovery-yaourt-granola-fruits-toast-oeufs": {
    calories: 610,
    proteinG: 32,
    carbsG: 65,
    fatG: 20,
    preparationType: "assemblage_sec",
    accent: "#d9c47c",
    ingredients: ["Yaourt grec", "Granola", "Banane", "Fruits rouges", "Miel", "Pain complet", "Oeufs", "Avocat"],
    allergens: ["Lait", "Gluten", "Oeufs"],
    ingredientNotes: "Format recovery complet et pratique, ideal quand il faut glucides, proteines et hydration douce sans plat chaud lourd.",
  },
  "hydration-electrolyte-mix": {
    calories: 180,
    proteinG: 12,
    carbsG: 18,
    fatG: 4,
    preparationType: "assemblage_sec",
    accent: "#6cd3ff",
    ingredients: ["Eau purifiee", "Poudre de coco", "Dextrose", "Jus de citron", "Citrate de sodium", "Citrate de magnesium", "Chlorure de potassium", "Arome naturel citron"],
    allergens: [],
    ingredientNotes: "Ancien melange FEATNESS conserve pour l'historique produit.",
  },
  "recovery-protein-mix": {
    calories: 340,
    proteinG: 28,
    carbsG: 35,
    fatG: 8,
    preparationType: "auto_chauffant",
    accent: "#ffb86b",
    ingredients: ["Isolat de whey", "Farine d'avoine", "Banane dehydratee", "Cacao maigre", "Lecithine de tournesol", "Arome naturel vanille"],
    allergens: ["Lait", "Gluten"],
    ingredientNotes: "Ancien melange FEATNESS conserve pour l'historique produit.",
  },
  "endurance-carb-blend": {
    calories: 290,
    proteinG: 14,
    carbsG: 44,
    fatG: 6,
    preparationType: "lyophilise",
    accent: "#9ff58f",
    ingredients: ["Flocons d'avoine", "Maltodextrine", "Poudre de datte", "Puree d'amande", "Sel marin", "Arome naturel fruits rouges"],
    allergens: ["Fruits a coque", "Gluten"],
    ingredientNotes: "Ancien melange FEATNESS conserve pour l'historique produit.",
  },
};

export const DEFAULT_MEAL_PRESENTATION: MealCatalogPresentation = {
  calories: 250,
  proteinG: 18,
  carbsG: 30,
  fatG: 7,
  preparationType: "assemblage_sec",
  accent: "#c9a646",
  ingredients: ["Base nutrition FEATNESS"],
  allergens: [],
  ingredientNotes: "Fiche ingredient detaillee a completer.",
};

const LIGHT_EFFORT_SLUGS = new Set([
  "bowl-poulet-riz-courgette",
  "omelette-sport-tartines-completes",
  "skyr-bowl-banane-flocons-davoine",
  "wrap-dinde-avocat",
  "saumon-pommes-de-terre-haricots-verts",
  "porridge-proteine-post-cardio",
]);

const MEDIUM_EFFORT_SLUGS = new Set([
  "poulet-patate-douce-brocoli",
  "bowl-quinoa-thon-avocat",
  "pates-completes-au-poulet",
  "riz-boeuf-maigre-poivrons",
  "chili-leger-recuperation",
  "salade-lentilles-oeufs-feta",
  "burrito-bowl-dinde-riz",
  "cabillaud-semoule-legumes-rotis",
]);

export function getEffortCategoryForSlug(slug: string): EffortCategory {
  if (LIGHT_EFFORT_SLUGS.has(slug)) {
    return "light";
  }

  if (MEDIUM_EFFORT_SLUGS.has(slug)) {
    return "medium";
  }

  return "intense";
}
